const Service = require("../models/Service");
const cloudinary = require("../config/cloudinary");


// Upload image to Cloudinary
const uploadToCloudinary = (fileBuffer) => {
  return new Promise((resolve, reject) => {

    const stream = cloudinary.uploader.upload_stream(
      {
        folder: "services",
      },

      (error, result) => {

        if (error) return reject(error);

        resolve(result);

      }
    );


    stream.end(fileBuffer);

  });
};


// GET ALL SERVICES (Newest first, paginated)
// Query params: ?page=1&limit=10
// Mirrors Post's getPosts: language-scoped filter always applied, plus
// status "active" so the public page never has to filter client-side.
exports.getServices = async (req, res) => {

  try {

    const page = parseInt(req.query.page) || 1;
    const limit = parseInt(req.query.limit) || 10;
    const skip = (page - 1) * limit;

    // language-scoped filter, always applied
    const filter = {
      status: "active",
      language: req.language
    };

    if (req.query.category) {
      filter.category = req.query.category;
    }

    const [services, totalServices] = await Promise.all([

      Service.find(filter)
        .populate("language", "name code")
        .sort({ createdAt: -1, _id: -1 })
        .skip(skip)
        .limit(limit),

      Service.countDocuments(filter)

    ]);

    res.json({

      services,

      currentPage: page,

      totalPages: Math.ceil(totalServices / limit),

      totalServices

    });


  } catch (err) {

    res.status(500).json({
      message: err.message
    });

  }

};


// GET SINGLE SERVICE
exports.getServiceById = async (req, res) => {

  try {

    const service = await Service.findById(req.params.id)
      .populate("language", "name code");


    if (!service) {

      return res.status(404).json({
        message: "Service not found"
      });

    }


    res.json(service);


  } catch (err) {

    res.status(500).json({
      message: err.message
    });

  }

};


// CREATE SERVICE
exports.createService = async (req, res) => {

  try {

    let imageUrl = "";


    if (req.file) {

      const result = await uploadToCloudinary(
        req.file.buffer
      );

      imageUrl = result.secure_url;

    }


    const service = new Service({

      title: req.body.title,

      description: req.body.description,

      imageUrl: imageUrl,

      day: req.body.day,

      time: req.body.time,

      category: req.body.category,

      language: req.body.language,

      location: req.body.location,

      isFeatured:
        req.body.isFeatured || false,

      status:
        req.body.status || "active"

    });


    const savedService = await service.save(); // schedule auto-generated by pre("save") hook


    res.status(201).json(savedService);


  } catch (err) {


    console.error(err);


    res.status(500).json({

      message: "Failed to create service",

      error: err.message

    });


  }

};


// UPDATE SERVICE
exports.updateService = async (req, res) => {


  try {


    const service = await Service.findById(req.params.id);


    if (!service) {

      return res.status(404).json({

        message: "Service not found"

      });

    }


    if (req.file) {

      const result = await uploadToCloudinary(
        req.file.buffer
      );

      service.imageUrl = result.secure_url;

    }


    // apply any other updated fields sent in the body
    Object.assign(service, req.body);


    service.updatedAt = Date.now();


    const updatedService = await service.save(); // triggers pre("save") hook, rebuilds schedule if day/time changed


    res.json(updatedService);


  } catch (err) {


    res.status(500).json({

      message: err.message

    });


  }


};


// DELETE SERVICE
exports.deleteService = async (req, res) => {


  try {


    const service =
      await Service.findByIdAndDelete(
        req.params.id
      );


    if (!service) {

      return res.status(404).json({

        message: "Service not found"

      });

    }


    res.json({

      message: "Service deleted successfully"

    });


  } catch (err) {


    res.status(500).json({

      message: err.message

    });


  }


};


// GET FEATURED SERVICES
exports.getFeaturedServices = async (req, res) => {


  try {


    const services = await Service.find({

      isFeatured: true,

      status: "active",

      language: req.language

    })
      .populate("language", "name code")
      .sort({

        createdAt: -1

      });


    res.json(services);


  } catch (err) {


    res.status(500).json({

      message: err.message

    });


  }


};


// GET ACTIVE SERVICES
exports.getActiveServices = async (req, res) => {


  try {


    const services = await Service.find({

      status: "active",

      language: req.language

    })
      .populate("language", "name code")
      .sort({

        createdAt: -1

      });


    res.json(services);


  } catch (err) {


    res.status(500).json({

      message: err.message

    });


  }


};